# Generated by Django 3.1.5 on 2021-01-12 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simplification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_content', models.TextField()),
                ('corrected_content', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, choices=[('a1', 'Leichte Sprache'), ('a2', 'Einfache Sprache'), ('b2', 'Vereinfachte Sprache'), ('c2', 'Alltagssprache')], max_length=50)),
                ('annotator', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
